#ifndef _ERROR_H_
#define _ERROR_H_

/*mqtt´íÎóÂë*/
#define MQTT_MSG_ERRORCODE_SUCCESS         0
#define MQTT_MSG_ERRORCODE_OPERATIONFAIL   1
#define MQTT_MSG_ERRORCODE_NORESPONSE      2
#define MQTT_MSG_ERRORCODE_FORMATERROR     3
#define MQTT_MSG_ERRORCODE_BUSY            4
#define MQTT_MSG_ERRORCODE_DEVICENOEXIST   5
#define MQTT_MSG_ERRORCODE_DEVICEOFFLINE   6


#endif
